{
	"version": 1541644119,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/light_ball-sheet0.png",
		"images/tiledbackground.png",
		"images/bigpuff.png",
		"images/littlepuff.png",
		"images/ghost-sheet0.png",
		"images/light_marker1-sheet0.png",
		"images/light_fade-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/particles.png",
		"images/startbutton-sheet0.png",
		"images/startglow-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/danger_zone-sheet0.png",
		"images/sprite-sheet0.png",
		"images/book_particle.png",
		"images/vortex-sheet0.png",
		"images/particles2.png",
		"images/sprite5-sheet0.png",
		"images/vortex_orbit-sheet0.png",
		"images/next_level_port2-sheet0.png",
		"images/next_level_port1-sheet0.png",
		"images/background_black.png",
		"images/end_ghost-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/walls-sheet0.png",
		"images/brickblock-sheet0.png",
		"media/menu click 2.m4a",
		"media/menu click 2.ogg",
		"media/oooscary1.m4a",
		"media/oooscary1.ogg",
		"media/oops1.m4a",
		"media/oops1.ogg",
		"media/menu click 3.m4a",
		"media/menu click 3.ogg",
		"media/bump1.m4a",
		"media/bump1.ogg",
		"media/airshot1.m4a",
		"media/airshot1.ogg",
		"media/startup2.m4a",
		"media/startup2.ogg",
		"media/mansion (exterior) - luigi's mansion.m4a",
		"media/mansion (exterior) - luigi's mansion.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"penumbra.png",
		"pathfind.js"
	]
}